### ISSUE TITLE
`use_systemd_nspawn` does not seem to work

### ISSUE THREAD

**Issue by chetbox** [pguyot/arm-runner-action#29]
My job looks like this:

```yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-01-28/2022-01-28-raspios-bullseye-arm64.zip
          cpu: cortex-a53 # arm64
          image_additional_mb: 4096
          bind_mount_repository: true
          use_systemd_nspawn: true
          shell: /bin/bash
          commands: ...
```

But I get this error:

```
 + sudo systemd-nspawn -D /home/actions/temp/arm-runner/mnt /tmp/commands.sh
Spawning container mnt on /home/actions/temp/arm-runner/mnt.
Press ^] three times within 1s to kill container.
/home/actions/temp/arm-runner/mnt/dev is pre-mounted and pre-populated. If a pre-mounted /dev is provided it needs to be an unpopulated file system.
mknod(/home/actions/temp/arm-runner/mnt/dev/null) failed: File exists
```

I'm not familiar with `systemd-nspawn` but it seems we should be using it given our `commands` include `systemctl enable ...`.
