### ISSUE TITLE
Copy artifact inside image to outside

### ISSUE THREAD

**Issue by patrickelectric** [pguyot/arm-runner-action#3]
Is that possible ? 
I did try to use the parameters `copy_artifact_path`, but it appears something outside the image to be inside, but I'm looking the other way around to output the binary.

**Comment by pguyot** [comment]
With `copy_artifact_path` and `copy_artifact_dest`, you can copy an artifact from the image (generated by your build commands), outside the image, before the image is unmounted.

The actual copy command is:
```
sudo cp -Rp ${{ steps.mount_image.outputs.mount }}${repository_path}/${{ inputs.copy_artifact_path }} ${{ inputs.copy_artifact_dest }}
```
https://github.com/pguyot/arm-runner-action/blob/main/action.yml#L96


The usage would be something like:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v1
      id: build_image
      copy_artifact_path: /tmp/my-file.txt
      copy_artifact_dest: .
      with:
        commands: |
            touch /tmp/my-file.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/releng' || startsWith(github.ref, 'refs/tags/')
      with:
        name: Generated artifact
        path: my-file.txt
```

Is it what you are trying to achieve?

**Comment by patrickelectric** [comment]
I just tested and it does not work, you can check it running here:
https://github.com/patrickelectric/mavlink-router/runs/2889100688?check_suite_focus=true#step:4:1

```
arm-v6:
  name: ARM v6 binary
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v1
      with:
        copy_artifact_path: touch mavlink-routerd-libc-armv6
        image_additional_mb: 1024
        commands: |
          touch mavlink-routerd-libc-armv6
    - name: Rename
      run: ls
    - uses: actions/upload-artifact@master
      with:
        path: mavlink-routerd-libc-armv6
```
