### ISSUE TITLE
Installing apt packages 

### ISSUE THREAD

**Issue by ithinkido** [pguyot/arm-runner-action#42]
I would like to install some apt packages and I am running into a warning about unknown host type.
```
sudo apt update 
Unknown host QEMU_IFLA type: 54`
```
this is using a modified test example template from [here](https://github.com/pguyot/arm-runner-action/blob/main/.github/workflows/test-aarch64.yml) 
```
name: Test aarch64 cpu option
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@HEAD
      with:
        base_image: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z
        cpu: cortex-a53
        commands: |
            echo "Minimal"
            test `uname -m` = 'aarch64'
            sudo apt update
            sudo apt-get install -y git python3-pip libgeos-c1v5 libatlas-base-dev python3-venv 
```
Is there a way to make sure of the correct apt package for each platform ?
