### ISSUE TITLE
add support for ubuntu raspi

### ISSUE THREAD

**Issue by razr** [pguyot/arm-runner-action#47]
thanks for your great project, I have tried to use it with ubuntu raspi as:
```yaml
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: https://cdimage.ubuntu.com/releases/22.04.1/release/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img.xz
        commands: |
            uname -a
```
and get

```bash
cp: cannot stat '/home/actions/temp/arm-runner/mnt/etc/resolv.conf': No such file or directory
cp: not writing through dangling symlink '/home/actions/temp/arm-runner/mnt/etc/resolv.conf'
```

I think this is because:

```
ls -la /etc/resolv.conf
/etc/resolv.conf -> ../run/resolvconf/resolv.conf
```
