### ISSUE TITLE
which cpu to configure for a Revolution PI?

### ISSUE THREAD

**Issue by sv3ndk** [pguyot/arm-runner-action#73]
Hi,

I'm failing to figure out how to configure `arm-runner-action` to compile for a Revolution Pi.

The output of `lscpu` tells me I have a Cortex-72 on an `armv7l` platform:

```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            270.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

And I'm currently using Raspbian buster:  `uname -a`  : 
```
Linux RevPi 5.10.120-rt70-v7l #1 SMP PREEMPT_RT Thu, 28 Jul 2022 10:36:48 +0200 armv7l GNU/Linux
```

I've therefore tried to use `raspbian_lite:2020-02-13` with `cortex-a72`:

```
      - name: building
        uses: pguyot/arm-runner-action@v2
        with:
          bind_mount_repository: true
          base_image: 'raspbian_lite:2020-02-13'
          cpu: cortex-a72
          commands: |
            apt update
            ...
```

But the process fails to resolve the CPU:

```
qemu-arm-static0: unable to find CPU model 'cortex-a72'
```

Would you have any suggestion what configuration might work?

Thanks!
