### ISSUE TITLE
No networking inside DietPi image

### ISSUE THREAD

**Issue by bvobart** [pguyot/arm-runner-action#91]
Hi there. I'm trying to make a custom DietPi image with some pre-installed software, but apparently there is no network connectivity during the commands execution. How do I fix this?

### Reproducible Example

```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          base_image: dietpi:rpi_armv8_bullseye
          cpu: cortex-a53
          image_additional_mb: 500
          commands: |
            ping -4nc 1 -W 10 9.9.9.9
```

### Expected output

I expect the ping to succeed and thus show that there is network connectivity in the emulated DietPi image during commands execution.

### Actual output

```
 PING 9.9.9.9 (9.9.9.9) 56(84) bytes of data.

--- 9.9.9.9 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```
